CREATE DATABASE IF NOT EXISTS comunicate_db;
USE comunicate_db;

CREATE TABLE IF NOT EXISTS users (
    id INT UNIQUE NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    correo VARCHAR(100) NOT NULL,
    idToken VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS amigos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    idUsuario INT NOT NULL,
    idAmigo INT NOT NULL,
    idSolicitud INT DEFAULT 0,
    CONSTRAINT fk_usuario FOREIGN KEY(idUsuario) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_amigo FOREIGN KEY(idAmigo) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS historial (
    id INT PRIMARY KEY AUTO_INCREMENT,
    idUsuario INT NOT NULL,
    idAmigo INT NOT NULL,
    mensaje VARCHAR(256) NOT NULL,
    CONSTRAINT fk_husuario FOREIGN KEY(idUsuario) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_hamigo FOREIGN KEY(idAmigo) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);